<a href="https://colab.research.google.com/github/quaocalebfianku/Hamoye-Data-Science-Internship./blob/main/Hamoye_StageB_Caleb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression          #used for linear regression model
from sklearn.metrics import mean_absolute_error            #used for cal. MAE
from sklearn.preprocessing import MinMaxScaler             #used for normalising dataset into a common scale using Min and Max.
from sklearn.model_selection import train_test_split       #used for splitting dataset into training and testing df

from sklearn.metrics import mean_squared_error            #used for Residual Sum of Squares(RSS)
from sklearn.metrics import r2_score                      #used for R- Squares

#Penalisation Methods
from sklearn.linear_model import Ridge                    #used for L2 Regularisation
from sklearn.linear_model import Lasso                    #used for LASSO

print('Libraries Setup Completed!')

Libraries Setup Completed!

In [2]:
energydata_df = pd.read_csv("/content/energydata_complete.csv")

In [3]:
energydata_df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
#Show the last 5 rows

energydata_df.tail()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
19730,2016-05-27 17:20:00,100,0,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.7,...,23.2,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19731,2016-05-27 17:30:00,90,0,25.500000,46.500000,25.754000,42.080000,27.133333,41.223333,24.7,...,23.2,46.7900,22.600000,755.2,56.000000,3.500000,24.500000,13.300000,49.282940,49.282940
19732,2016-05-27 17:40:00,270,10,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.7,...,23.2,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,2016-05-27 17:50:00,420,10,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.7,...,23.2,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,2016-05-27 18:00:00,430,10,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.7,...,23.2,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [5]:
energydata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [6]:
#Printing rows and columns
energydata_df.shape[0], energydata_df.shape[1]

(19735, 29)

In [7]:
energydata_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [8]:
missing_values = pd.DataFrame({'Count':energydata_df.isna().sum(),'Percentage':energydata_df.isna().sum()/len(energydata_df)*100})
missing_values

             Count  Percentage
date             0         0.0
Appliances       0         0.0
lights           0         0.0
T1               0         0.0
RH_1             0         0.0
T2               0         0.0
RH_2             0         0.0
T3               0         0.0
RH_3             0         0.0
T4               0         0.0
RH_4             0         0.0
T5               0         0.0
RH_5             0         0.0
T6               0         0.0
RH_6             0         0.0
T7               0         0.0
RH_7             0         0.0
T8               0         0.0
RH_8             0         0.0
T9               0         0.0
RH_9             0         0.0
T_out            0         0.0
Press_mm_hg      0         0.0
RH_out           0         0.0
Windspeed        0         0.0
Visibility       0         0.0
Tdewpoint        0         0.0
rv1              0         0.0
rv2              0         0.0

**Question 17 :**
From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the Root Mean Squared error in three D.P?

In [9]:
x = energydata_df['T2'].values.reshape(-1, 1)  # Independent variable
y = energydata_df['T6'].values  # Dependent variable

# Create and fit the linear regression model
model = LinearRegression()
model.fit(x, y)

# Make predictions
y_pred = model.predict(x)

# Calculate the RMSE
rmse = np.sqrt(mean_squared_error(y, y_pred))

# Print RMSE rounded to three decimal places
print(f'RMSE: {rmse:.3f}')

RMSE: 3.644

**Question 18 :**
Remove the following columns: [“date”, “lights”]. The target variable is “Appliances”. Use a 70-30 train-test set split with a  random state of 42 (for reproducibility). Normalize the dataset using the MinMaxScaler (Hint: Use the MinMaxScaler fit_transform and transform methods on the train and test set respectively). Run a multiple linear regression using the training set. Answer the following questions:

What is the Mean Absolute Error (in three decimal places) for the  training set?

In [10]:
columns_to_remove = ["date", "lights"]
energydata_df = energydata_df.drop(columns=columns_to_remove)

# Define the features (independent variables) and the target variable
X = energydata_df.drop(columns=["Appliances"])
y = energydata_df["Appliances"]

# Split the data into a training set and a test set (70-30 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the dataset using MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train a multiple linear regression model on the training set
model = LinearRegression()
model.fit(X_train_scaled, y_train)

# Make predictions on the training set
y_train_pred = model.predict(X_train_scaled)

# Calculate the Mean Absolute Error (MAE) for the training set
mae = mean_absolute_error(y_train, y_train_pred)

# Print MAE rounded to three decimal places
print(f"Mean Absolute Error (training set): {mae:.3f}")

Mean Absolute Error (training set): 53.742

**Question 19 :**
What is the Root Mean Squared Error (in three decimal places) for the training set?

In [12]:
# Calculate the Mean Squared Error (MSE) for the training set
mse = mean_squared_error(y_train, y_train_pred)

# Calculate the RMSE
rmse = (mse ** 0.5)

# Print RMSE rounded to three decimal places
print(f"Root Mean Squared Error (training set): {rmse:.3f}")

Root Mean Squared Error (training set): 95.216

**Question 20:**
What is the Mean Absolute Error (in three decimal places) for test set?

In [13]:

# Make predictions on the test set
y_test_pred = model.predict(X_test_scaled)

# Calculate the Mean Absolute Error (MAE) for the test set
mae = mean_absolute_error(y_test, y_test_pred)

# Print MAE rounded to three decimal places
print(f"Mean Absolute Error (test set): {mae:.3f}")

Mean Absolute Error (test set): 53.643

**Question 21:**
What is the Root Mean Squared Error (in three decimal places) for test set?

In [14]:
# Calculate the Mean Squared Error (MSE) for the test set
mse = mean_squared_error(y_test, y_test_pred)

# Calculate the RMSE
rmse = (mse ** 0.5)

# Print RMSE rounded to three decimal places
print(f"Root Mean Squared Error (test set): {rmse:.3f}")

Root Mean Squared Error (test set): 93.640

**Question 24:**
Train a lasso regression model with default value and obtain the new feature weights with it. How many of the features have non-zero feature weights?

In [15]:
lasso_model = Lasso()

lasso_model.fit(X_train_scaled, y_train)

feature_weights = lasso_model.coef_

# Count the number of features with non-zero feature weights
num_nonzero_features = len(feature_weights[feature_weights != 0])

print(f"Number of features with non-zero feature weights: {num_nonzero_features}")

Number of features with non-zero feature weights: 4

**Question 25:**
What is the new RMSE with the Lasso Regression on the test set?

In [16]:
# Make predictions on the test set using Lasso regression
y_test_pred_lasso = lasso_model.predict(X_test_scaled)

# Calculate the RMSE for Lasso regression on the test set
mse_test_lasso = mean_squared_error(y_test, y_test_pred_lasso)
rmse_test_lasso = (mse_test_lasso ** 0.5)

print(f"RMSE (Lasso Regression on test set): {rmse_test_lasso:.3f}")

RMSE (Lasso Regression on test set): 99.424